### ISSUE TITLE
Device type is shifted to the right with long names

### ISSUE THREAD

**Issue by Aircoookie** [YeonV/wled-manager#1]
This project is awesome! v0.0.1 is already very impressive :) Thank you for your work!

Noticed one tiny issue: The device type (ESP8266/ESP32) is moved to the right if the device name is too long.
I would propose either shortening the device name string with ... or hiding the device type in case the name is too wide.

![shift](https://user-images.githubusercontent.com/21045690/134747590-3cdc2368-4d82-4b53-96d7-6d655925f871.PNG)

Excited to see the future of this 🎉

**Comment by YeonV** [comment]
@Aircoookie  the god himself :)

Thank you very much

incoming in 0.0.3

![image](https://user-images.githubusercontent.com/28861537/135349951-580d898f-b4de-46d4-a8d0-f471a9c797bd.png)

- less padding
- smaller font
- string cutted off (but `...` not added)

**Comment by YeonV** [comment]
@Aircoookie Check [v0.0.3](https://github.com/YeonV/wled-manager/releases/tag/v0.0.3) :)
