### ISSUE TITLE
Only white screen

### ISSUE THREAD

**Issue by AriaFantom** [YeonV/wled-manager#2]
![image](https://user-images.githubusercontent.com/55119711/176500988-b11e60a1-afc6-4b36-9ed7-21bdb61026e6.png)

There is this white screen doesnt show up anything 
I am on windows 11

**Comment by YeonV** [comment]
oops sry, latest release is bugged. use 0.0.9 atm

**Comment by YeonV** [comment]
@AriaFantom Sorry this project got lost.
Just fixed the windows release builds for 0.1.0
